version: '3'
services:
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.15.1
    command: ["-f", "/usr/share/logstash/pipeline/logstash.conf", "--path.settings", "/usr/share/logstash/pipeline/"]
    volumes:
      - /tmp/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      S3_ID_1: "sample-id-1"
      AWS_BUCKET_1: "aws-bucket-name"
      FOLDER_PREFIX_1: "bucket-folder-prefix-1"
      S3_ID_2: "sample-id-2"
      FOLDER_PREFIX_2: "bucket-folder-prefix-2"
      AWS_BUCKET_2: "aws-bucket-name"
      ROLE_ARN: "other-account-role-arn"
      AWS_REGION: "aws-region"
      AWS_ACCESS_KEY_ID: "aws_access_key_id"
      AWS_SECRET_ACCESS_KEY: "aws_secret_access_key"
    networks:
      - otel_network
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"
      - "2255:2255"
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yaml
    networks:
      - otel_network

networks:
  otel_network:
    driver: bridge


